/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HomeLazyImport = createFileRoute('/home')()
const IndexLazyImport = createFileRoute('/')()
const CypherDashboardLazyImport = createFileRoute('/cypher/dashboard')()
const ClientDashboardLazyImport = createFileRoute('/client/dashboard')()

// Create/Update Routes

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CypherDashboardLazyRoute = CypherDashboardLazyImport.update({
  path: '/cypher/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cypher/dashboard.lazy').then((d) => d.Route),
)

const ClientDashboardLazyRoute = ClientDashboardLazyImport.update({
  path: '/client/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/client/dashboard.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/client/dashboard': {
      preLoaderRoute: typeof ClientDashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/cypher/dashboard': {
      preLoaderRoute: typeof CypherDashboardLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  HomeLazyRoute,
  ClientDashboardLazyRoute,
  CypherDashboardLazyRoute,
])

/* prettier-ignore-end */
